import type { RequestRecordDraftPayload } from '../store/request-records';

export interface RequestRequirementProjectDefinition {
  id: string;
  title: string;
  description: string;
  placeholder: string;
  quickOptions: string[];
  hint: string;
  required: true;
  allowExplicitNone?: boolean;
  forbidContainingNoneText?: boolean;
}

export interface RequestRequirementCategoryDefinition {
  id: string;
  field: keyof RequestRecordDraftPayload;
  order: number;
  title: string;
  description?: string;
  projects: RequestRequirementProjectDefinition[];
}

export const REQUEST_REQUIREMENT_CATEGORIES: RequestRequirementCategoryDefinition[] = [
  {
    id: 'background',
    field: 'userRequirementBackground',
    order: 1,
    title: '背景',
    description: '确认本次申请的业务背景与目标。',
    projects: [
      {
        id: 'purpose',
        title: '1.1 申请目的 / 背景',
        description: '本次申请的主要业务背景、项目目标或阶段。',
        placeholder: '为经销商门户 UAT 环境申请资源，验证登录和订单查询链路。',
        quickOptions: ['新增功能上线', 'UAT 联调', 'SIT 测试', '生产扩容', '压测验证', 'POC 试点'],
        hint: '评审时判断业务优先级、上线计划和资源紧急程度。',
        required: true,
        allowExplicitNone: false,
        forbidContainingNoneText: true,
      },
    ],
  },
  {
    id: 'users',
    field: 'userRequirementUsers',
    order: 2,
    title: '用户相关',
    description: '使用本系统的用户特征与访问方式。',
    projects: [
      {
        id: 'userGroup',
        title: '2.1 使用用户群体',
        description: '最终使用本系统的用户类型。',
        placeholder: '内部员工 + 经销商',
        quickOptions: ['内部员工', '经销商', '合作伙伴', '外部客户', '供应商'],
        hint: '决定公网访问、安全边界、认证方式和网络策略。',
        required: true,
        allowExplicitNone: true,
      },
      {
        id: 'userScale',
        title: '2.2 用户规模 / 并发量',
        description: '预估用户数量、同时在线数或并发请求数。',
        placeholder: '日均 1000 人访问，峰值并发 200。',
        quickOptions: ['日均 1000 人', '峰值并发 200', '日活 1 万', '峰值并发 1000'],
        hint: '直接影响规格档位、集群方案和扩展性设计。',
        required: true,
        allowExplicitNone: true,
      },
      {
        id: 'userRegion',
        title: '2.3 用户使用地域',
        description: '用户主要访问地域。',
        placeholder: '中国大陆（华南区为主）',
        quickOptions: ['中国大陆', '海外', '华南区', '华北区', '工厂园区'],
        hint: '用于判断网络区域、时延要求和跨境合规。',
        required: true,
        allowExplicitNone: true,
      },
      {
        id: 'userTime',
        title: '2.4 用户使用时间分布',
        description: '业务高峰时段。',
        placeholder: '工作日 9:00-18:00，月末访问量翻倍。',
        quickOptions: ['工作日 9-18 点', '月末集中', '季度末集中', '7×24 均匀'],
        hint: '帮助设计弹性扩缩容、维护窗口和压测计划。',
        required: true,
        allowExplicitNone: true,
      },
      {
        id: 'userAccess',
        title: '2.5 用户访问方式',
        description: '用户通过何种终端访问。',
        placeholder: 'PC Web + H5 混合',
        quickOptions: ['PC Web', 'H5', 'App', '小程序', 'API', '多终端混合'],
        hint: '影响域名发布、认证链路和移动端适配要求。',
        required: true,
        allowExplicitNone: false,
        forbidContainingNoneText: true,
      },
      {
        id: 'userRole',
        title: '2.6 用户权限 / 角色要求',
        description: '是否需要分角色、分权限。',
        placeholder: '管理员、普通用户、只读用户。',
        quickOptions: ['管理员', '普通用户', '只读用户', '审批角色', '业务角色'],
        hint: '评审数据权限隔离和后台管理需求。',
        required: true,
        allowExplicitNone: true,
      },
      {
        id: 'userAuth',
        title: '2.7 用户认证方式',
        description: '登录认证方式。',
        placeholder: '统一认证（SSO）',
        quickOptions: ['统一认证（SSO）', 'AD 域账号', '短信验证码', 'OAuth2', 'LDAP'],
        hint: '决定是否需要对接统一认证、AD 域或 OAuth 服务。',
        required: true,
        allowExplicitNone: true,
      },
    ],
  },
  {
    id: 'ops',
    field: 'userRequirementOps',
    order: 3,
    title: '运维相关',
    description: '服务时间、备份、监控与运维分工。',
    projects: [
      {
        id: 'serviceTime',
        title: '3.1 服务时间 / 可用性要求',
        description: '系统需要的服务时间。',
        placeholder: '7×24',
        quickOptions: ['7×24', '5×8', '工作日 8-20 点'],
        hint: '决定是否需要高可用、双活或容灾方案。',
        required: true,
        allowExplicitNone: true,
      },
      {
        id: 'maintenanceWindow',
        title: '3.2 维护窗口',
        description: '可接受的停机维护时段。',
        placeholder: '每周日凌晨 2:00-6:00',
        quickOptions: ['每周日凌晨 2-6 点', '工作日 22-6 点', '无固定窗口'],
        hint: '用于安排补丁更新、发布窗口和计划内停机。',
        required: true,
        allowExplicitNone: true,
      },
      {
        id: 'backup',
        title: '3.3 备份 / 恢复要求',
        description: '数据备份策略与恢复要求。',
        placeholder: '每日全量备份，保留 7 天。',
        quickOptions: ['每日全量', '每日增量', '每周全量', '保留 7 天', '保留 30 天'],
        hint: '评审 RTO/RPO 和数据恢复能力。',
        required: true,
        allowExplicitNone: true,
      },
      {
        id: 'monitor',
        title: '3.4 监控 / 告警要求',
        description: '是否需要接入监控告警。',
        placeholder: '接入统一监控平台，CPU>80% 告警。',
        quickOptions: ['接入统一监控平台', 'CPU>80% 告警', '内存>80% 告警', '磁盘>80% 告警', '接口失败率告警'],
        hint: '影响监控接入、告警策略和运维交接。',
        required: true,
        allowExplicitNone: true,
      },
      {
        id: 'opsOwner',
        title: '3.5 运维责任分工',
        description: '应用运维与基础设施运维分工。',
        placeholder: '应用层由业务方负责，OS 层由云运维负责。',
        quickOptions: ['业务方负责应用', '云运维负责 OS', '共同负责', '待定'],
        hint: '明确后续故障处理、权限申请和变更责任方。',
        required: true,
        allowExplicitNone: true,
      },
    ],
  },
  {
    id: 'security',
    field: 'userRequirementOps',
    order: 4,
    title: '安全要件',
    description: '数据安全、访问控制、审计与合规。',
    projects: [
      {
        id: 'dataSecurity',
        title: '4.1 数据安全 / 加密要求',
        description: '数据传输和存储加密。',
        placeholder: 'HTTPS 传输，数据库敏感字段加密。',
        quickOptions: ['HTTPS 传输', '数据库敏感字段加密', 'TLS', 'AES 加密'],
        hint: '评审数据加密、脱敏和传输安全要求。',
        required: true,
        allowExplicitNone: true,
      },
      {
        id: 'accessControl',
        title: '4.2 访问控制要求',
        description: '网络隔离、白名单、防火墙。',
        placeholder: '仅内网访问，指定 IP 白名单。',
        quickOptions: ['仅内网访问', '指定 IP 白名单', '堡垒机访问', 'VPN 访问'],
        hint: '影响网络区域划分、安全组和防火墙策略。',
        required: true,
        allowExplicitNone: true,
      },
      {
        id: 'audit',
        title: '4.3 审计 / 日志要求',
        description: '操作审计和日志保留。',
        placeholder: '操作日志保留 180 天。',
        quickOptions: ['操作日志保留 180 天', '访问日志保留 90 天', '审计日志保留 1 年'],
        hint: '决定日志采集、保留周期和审计合规。',
        required: true,
        allowExplicitNone: true,
      },
      {
        id: 'compliance',
        title: '4.4 合规要求',
        description: '等保、GDPR、行业合规。',
        placeholder: '等保三级',
        quickOptions: ['等保二级', '等保三级', 'GDPR', '行业合规'],
        hint: '影响安全架构、测评要求和材料准备。',
        required: true,
        allowExplicitNone: true,
      },
      {
        id: 'patch',
        title: '4.5 漏洞 / 补丁管理',
        description: '安全补丁和漏洞修复要求。',
        placeholder: '高危漏洞 7 个工作日内修复。',
        quickOptions: ['高危漏洞 7 个工作日', '高危漏洞 15 个工作日', '月度补丁更新'],
        hint: '明确漏洞修复 SLA 和运维流程。',
        required: true,
        allowExplicitNone: true,
      },
    ],
  },
  {
    id: 'cloud',
    field: 'userRequirementCloudService',
    order: 5,
    title: '云服务提供',
    description: '所需云服务类型与使用周期。',
    projects: [
      {
        id: 'cloudService',
        title: '5.1 所需云服务类型',
        description: '需要的云服务类别。',
        placeholder: '云主机、MySQL、Redis、负载均衡。',
        quickOptions: ['云主机', '对象存储', 'MySQL', 'Redis', 'RabbitMQ', 'Kafka', '负载均衡'],
        hint: '直接决定需要开通哪些云产品和组件能力。',
        required: true,
        allowExplicitNone: true,
      },
      {
        id: 'cloudCycle',
        title: '5.2 资源使用周期',
        description: '资源的预计使用时长。',
        placeholder: '6 个月（项目周期）',
        quickOptions: ['长期', '3 个月', '6 个月', '12 个月', '项目周期'],
        hint: '影响资源计费方式、到期提醒和回收策略。',
        required: true,
        allowExplicitNone: true,
      },
    ],
  },
  {
    id: 'middleware',
    field: 'userRequirementMiddleware',
    order: 6,
    title: '中间件 & 数据库',
    description: '数据库、中间件类型与性能容量预估。',
    projects: [
      {
        id: 'middlewareType',
        title: '6.1 数据库 / 中间件类型',
        description: '需要的具体产品。',
        placeholder: 'MySQL 8.0、Redis 6.x。',
        quickOptions: ['MySQL 8.0', 'Redis 6.x', 'RabbitMQ', 'Kafka', 'PostgreSQL', 'MongoDB'],
        hint: '决定组件能力选择和版本兼容性要求。',
        required: true,
        allowExplicitNone: true,
      },
      {
        id: 'middlewareCapacity',
        title: '6.2 性能 / 容量预估',
        description: 'TPS/QPS、数据量、连接数等。',
        placeholder: '日均 QPS 5000，峰值 QPS 20000，数据量 500GB。',
        quickOptions: ['日均 QPS 5000', '峰值 QPS 20000', '数据量 500GB', '连接数 1000'],
        hint: '用于核对规格档位、节点数和高可用方案。',
        required: true,
        allowExplicitNone: true,
      },
    ],
  },
  {
    id: 'server',
    field: 'userRequirementServer',
    order: 7,
    title: '服务器基础侧',
    description: '操作系统、计算规格与部署方式。',
    projects: [
      {
        id: 'os',
        title: '7.1 操作系统要求',
        description: 'OS 类型和版本。',
        placeholder: 'CentOS 7.9',
        quickOptions: ['CentOS 7.9', 'Rocky Linux 8', 'Windows Server 2019', 'Ubuntu 20.04'],
        hint: '影响镜像选择、补丁策略和许可合规。',
        required: true,
        allowExplicitNone: true,
      },
      {
        id: 'spec',
        title: '7.2 计算规格要求',
        description: 'CPU、内存、磁盘初步要求。',
        placeholder: '4C8G',
        quickOptions: ['2C4G', '4C8G', '8C16G', '16C32G'],
        hint: '初步规格，最终以评审和压测结果为准。',
        required: true,
        allowExplicitNone: true,
      },
      {
        id: 'deploy',
        title: '7.3 部署方式',
        description: '单机、集群、容器化等。',
        placeholder: '双机集群',
        quickOptions: ['单机部署', '双机集群', '3 节点集群', 'Kubernetes 容器', '主从架构'],
        hint: '决定高可用、故障转移和扩展方式。',
        required: true,
        allowExplicitNone: true,
      },
    ],
  },
  {
    id: 'network',
    field: 'userRequirementNetwork',
    order: 8,
    title: '网络需求',
    description: '网络区域、访问边界、域名与带宽。',
    projects: [
      {
        id: 'networkZone',
        title: '8.1 网络区域',
        description: '业务网、管理网、DMZ 等。',
        placeholder: '业务网 B 区',
        quickOptions: ['业务网 A 区', '业务网 B 区', '管理网', 'DMZ'],
        hint: '决定虚拟机部署的网络分区。',
        required: true,
        allowExplicitNone: true,
      },
      {
        id: 'publicAccess',
        title: '8.2 公网访问需求',
        description: '是否需要公网访问。',
        placeholder: '需要公网域名发布',
        quickOptions: ['不需要公网', '需要公网域名发布', '需要公网 IP', '仅内网'],
        hint: '影响域名、WAF、安全组和发布流程。',
        required: true,
        allowExplicitNone: true,
      },
      {
        id: 'domain',
        title: '8.3 域名 / DNS 需求',
        description: '是否需要域名和解析。',
        placeholder: '需要 xxx.company.com',
        quickOptions: ['需要新域名', '使用现有域名', '不需要域名', '需要 DNS 解析'],
        hint: '明确域名申请、解析变更和证书需求。',
        required: true,
        allowExplicitNone: true,
      },
      {
        id: 'loadBalancer',
        title: '8.4 负载均衡需求',
        description: '是否需要 LB。',
        placeholder: '需要 4 层负载均衡',
        quickOptions: ['4 层负载均衡', '7 层负载均衡', '不需要 LB'],
        hint: '决定高可用入口和流量分发方案。',
        required: true,
        allowExplicitNone: true,
      },
      {
        id: 'ports',
        title: '8.5 端口 / 协议需求',
        description: '需要开放的端口和协议。',
        placeholder: 'TCP 80/443/3306',
        quickOptions: ['TCP 80/443', 'TCP 3306', 'TCP 22', 'UDP 53'],
        hint: '用于开通常访策略和安全组规则。',
        required: true,
        allowExplicitNone: true,
      },
      {
        id: 'whitelist',
        title: '8.6 系统互访 / 白名单',
        description: '与其他系统的互访关系。',
        placeholder: '需访问订单中心 10.x.x.x:8080',
        quickOptions: ['需访问订单中心', '需访问统一认证', '需访问短信网关', '需访问报表平台'],
        hint: '明确上下游调用关系和网络策略。',
        required: true,
        allowExplicitNone: true,
      },
      {
        id: 'vpn',
        title: '8.7 专线 / VPN 需求',
        description: '是否需要专线或 VPN。',
        placeholder: '工厂通过专线访问',
        quickOptions: ['不需要', '工厂专线接入', 'SSL VPN', 'IPSec VPN'],
        hint: '影响跨地域、工厂或合作伙伴接入方案。',
        required: true,
        allowExplicitNone: true,
      },
      {
        id: 'bandwidth',
        title: '8.8 带宽 / 时延要求',
        description: '网络带宽和时延。',
        placeholder: '带宽 100Mbps，时延 < 50ms',
        quickOptions: ['10Mbps', '50Mbps', '100Mbps', '时延 < 50ms', '时延 < 100ms'],
        hint: '用于评估网络规划和链路质量。',
        required: true,
        allowExplicitNone: true,
      },
      {
        id: 'haNetwork',
        title: '8.9 高可用网络',
        description: '是否需要双网卡、双链路。',
        placeholder: '需要双网卡绑定',
        quickOptions: ['双网卡绑定', '双链路冗余', '单网卡', '不需要'],
        hint: '影响网络冗余和故障切换能力。',
        required: true,
        allowExplicitNone: true,
      },
      {
        id: 'cdn',
        title: '8.10 CDN / 加速需求',
        description: '是否需要 CDN。',
        placeholder: '静态资源使用 CDN',
        quickOptions: ['静态资源 CDN', '全站加速', '不需要'],
        hint: '明确静态资源加速和边缘分发需求。',
        required: true,
        allowExplicitNone: true,
      },
      {
        id: 'securityDevice',
        title: '8.11 网络安全设备',
        description: 'WAF、IPS 等。',
        placeholder: '公网入口需 WAF 防护',
        quickOptions: ['WAF', 'IPS', 'IDS', '防火墙', '不需要'],
        hint: '决定公网入口安全防护设备。',
        required: true,
        allowExplicitNone: true,
      },
    ],
  },
];
